// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7PFLS49UFFroBym_OAzBV86e8W7XnzGw',
    appId: '1:1046754751820:web:a109916db32f377cfccbe9',
    messagingSenderId: '1046754751820',
    projectId: 'labproject-dcfe8',
    authDomain: 'labproject-dcfe8.firebaseapp.com',
    storageBucket: 'labproject-dcfe8.firebasestorage.app',
    measurementId: 'G-24ER6CDREQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAauTy15K4Sr43KtVlaKT6hPQxgB6aLryc',
    appId: '1:1046754751820:android:b6c3f99678acd856fccbe9',
    messagingSenderId: '1046754751820',
    projectId: 'labproject-dcfe8',
    storageBucket: 'labproject-dcfe8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAV4PClOuIXc08Ku40ftXRZzNLXXimtGJY',
    appId: '1:1046754751820:ios:fa7ddb5d0c4db6a8fccbe9',
    messagingSenderId: '1046754751820',
    projectId: 'labproject-dcfe8',
    storageBucket: 'labproject-dcfe8.firebasestorage.app',
    iosBundleId: 'com.example.projectterminal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAV4PClOuIXc08Ku40ftXRZzNLXXimtGJY',
    appId: '1:1046754751820:ios:fa7ddb5d0c4db6a8fccbe9',
    messagingSenderId: '1046754751820',
    projectId: 'labproject-dcfe8',
    storageBucket: 'labproject-dcfe8.firebasestorage.app',
    iosBundleId: 'com.example.projectterminal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB7PFLS49UFFroBym_OAzBV86e8W7XnzGw',
    appId: '1:1046754751820:web:614f7beec1e2a21dfccbe9',
    messagingSenderId: '1046754751820',
    projectId: 'labproject-dcfe8',
    authDomain: 'labproject-dcfe8.firebaseapp.com',
    storageBucket: 'labproject-dcfe8.firebasestorage.app',
    measurementId: 'G-PF5HJMVL9D',
  );
}
